name: 'Generate Test Matrix'
description: 'Generate container test matrix based on changes detected'
inputs:
  libs-changed:
    description: 'Whether shared libraries have changed'
    required: true
  all-containers:
    description: 'Comma-separated list of all containers'
    required: true
  containers-changed:
    description: 'Comma-separated list of changed containers'
    required: true

outputs:
  matrix:
    description: 'JSON array of containers to test'
    value: ${{ steps.generate.outputs.matrix }}
  containers-count:
    description: 'Number of containers in the matrix'
    value: ${{ steps.generate.outputs.containers-count }}

runs:
  using: 'composite'
  steps:
    - name: Generate Container Test Matrix
      id: generate
      shell: bash
      env:
        LIBS_CHANGED: ${{ inputs.libs-changed }}
        ALL_CONTAINERS: ${{ inputs.all-containers }}
        CONTAINERS_CHANGED: ${{ inputs.containers-changed }}
      run: |
        echo "[MATRIX] Generating container test matrix..."

        # Validate inputs - only allow expected values
        if [[ "$LIBS_CHANGED" != "true" && "$LIBS_CHANGED" != "false" ]]; then
          echo "[ERROR] Invalid libs-changed value: $LIBS_CHANGED"
          exit 1
        fi

        if [ "$LIBS_CHANGED" = "true" ]; then
          # Test all containers if libs changed
          echo "[LIBS] Testing all containers due to libs change"
          matrix="$ALL_CONTAINERS"
          echo "Reason: Shared libraries modified - affects all containers"
        else
          # Test only changed containers
          echo "[CONTAINERS] Testing changed containers only"
          matrix="$CONTAINERS_CHANGED"
          echo "Reason: Only specific containers modified"
        fi

        # Validate matrix contains only allowed characters (alphanumeric, commas, hyphens, underscores)
        if [[ ! "$matrix" =~ ^[a-zA-Z0-9,_-]*$ ]]; then
          echo "[ERROR] Invalid characters in matrix: $matrix"
          echo "Only alphanumeric characters, commas, hyphens, and underscores are allowed"
          exit 1
        fi

        # Convert comma-separated to JSON array safely
        if [ -n "$matrix" ]; then
          # Remove any trailing/leading commas and empty entries
          matrix=$(echo "$matrix" | sed 's/^,\+//;s/,\+$//;s/,,\+/,/g')

          if [ -n "$matrix" ]; then
            containers_array=$(echo "$matrix" | sed 's/,/","/g' | sed 's/^/["/' | sed 's/$/"]/')
            containers_count=$(echo "$matrix" | tr ',' '\n' | wc -l)
          else
            containers_array='[]'
            containers_count=0
          fi
        else
          containers_array='[]'
          containers_count=0
        fi

        echo "[PASS] Generated matrix: $containers_array"
        echo "[STATS] Containers to test: $containers_count"

        # Output results
        echo "matrix=$containers_array" >> "$GITHUB_OUTPUT"
        echo "containers-count=$containers_count" >> "$GITHUB_OUTPUT"

        echo "[MATRIX] Test matrix generation completed"
