name: 'Infrastructure Quality Check'
description: 'Run infrastructure quality checks including Terraform formatting'
inputs:
  infra-changed:
    description: 'Whether infrastructure files changed'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Check Infrastructure Changes
      if: inputs.infra-changed != 'true'
      shell: bash
      run: |
        echo "No infrastructure changes detected, skipping infrastructure quality checks"
        exit 0

    - name: Run Infrastructure Checks
      if: inputs.infra-changed == 'true'
      shell: bash
      run: |
        echo "Running Terraform format check..."

        # Retry logic for Docker Hub transient failures
        MAX_RETRIES=3
        RETRY_DELAY=10

        for i in $(seq 1 $MAX_RETRIES); do
          echo "Attempt $i of $MAX_RETRIES..."

          if docker run --rm -v "$(pwd)/infra:/workspace" -w /workspace hashicorp/terraform:latest fmt -check -recursive .; then
            echo "Terraform format check passed"
            exit 0
          else
            EXIT_CODE=$?

            if [ $i -lt $MAX_RETRIES ]; then
              echo "Failed with exit code $EXIT_CODE. Retrying in ${RETRY_DELAY}s..."
              sleep $RETRY_DELAY
            else
              echo "Failed after $MAX_RETRIES attempts"
              exit $EXIT_CODE
            fi
          fi
        done
