# Dependabot configuration for AI Content Farm
# Features:
# - Auto-merge enabled for security updates and minor/patch versions
# - Manual review required for major version updates
# - Comprehensive testing via dependabot-automerge.yml workflow
# - Works with security scanning stack (Safety, Semgrep, Trivy, Checkov)
#
# Auto-merge criteria:
# - Security updates: Always auto-merged after CI validation
# - Patch/minor updates: Auto-merged after CI validation
# - Major updates: Require manual review
#
# Ref: https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Python dependencies - main workspace
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    labels:
      - "dependencies"
      - "python"
    reviewers:
      - "Hardcoreprawn"
    assignees:
      - "Hardcoreprawn"
    open-pull-requests-limit: 15
    # Enable auto-merge for security and patch updates
    pull-request-branch-name:
      separator: "/"

  # Python dependencies - container services
  - package-ecosystem: "pip"
    directory: "/containers/content-collector"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    labels:
      - "dependencies"
      - "python"
      - "content-collector"
    open-pull-requests-limit: 5

  - package-ecosystem: "pip"
    directory: "/containers/content-processor"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    labels:
      - "dependencies"
      - "python"
      - "content-processor"
    open-pull-requests-limit: 5

  - package-ecosystem: "pip"
    directory: "/containers/content-enricher"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    labels:
      - "dependencies"
      - "python"
      - "content-enricher"
    open-pull-requests-limit: 5

  - package-ecosystem: "pip"
    directory: "/containers/content-ranker"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    labels:
      - "dependencies"
      - "python"
      - "content-ranker"
    open-pull-requests-limit: 5

  - package-ecosystem: "pip"
    directory: "/containers/content-generator"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    labels:
      - "dependencies"
      - "python"
      - "content-generator"
    open-pull-requests-limit: 5

  - package-ecosystem: "pip"
    directory: "/containers/markdown-generator"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    labels:
      - "dependencies"
      - "python"
      - "markdown-generator"
    open-pull-requests-limit: 5

  - package-ecosystem: "pip"
    directory: "/containers/site-generator"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    labels:
      - "dependencies"
      - "python"
      - "site-generator"
    open-pull-requests-limit: 5

  - package-ecosystem: "pip"
    directory: "/containers/collector-scheduler"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    labels:
      - "dependencies"
      - "python"
      - "collector-scheduler"
    open-pull-requests-limit: 5

  # # Docker base images
  # - package-ecosystem: "docker"
  #   directory: "/containers"
  #   schedule:
  #     interval: "monthly"
  #     day: "monday"
  #     time: "06:00"
  #   labels:
  #     - "dependencies"
  #     - "docker"
  #   open-pull-requests-limit: 10

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "06:00"
    labels:
      - "dependencies"
      - "github-actions"
    open-pull-requests-limit: 5
