# Dependabot configuration for AI Content Farm (Monorepo Optimized)
#
# MONOREPO STRATEGY:
# - Consolidated dependency management across /containers/* and /functions/*
# - Reduced PR volume with strategic grouping
# - Coordinated with dependabot-automerge.yml workflow
# - Prevents workflow conflicts through batching and limits
#
# Auto-merge criteria (handled by dependabot-automerge.yml):
# - Security updates: Always auto-merged after CI validation
# - Patch/minor updates: Auto-merged after CI validation
# - Major updates: Require manual review with risk assessment
#
# Ref: https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # =============================================================================
  # SHARED LIBRARIES - Core dependencies used across containers
  # =============================================================================
  - package-ecosystem: "pip"
    directory: "/libs"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "UTC"
    labels:
      - "dependencies"
      - "python"
      - "libs"
      - "auto-merge"
    open-pull-requests-limit: 3
    # Group ALL libs updates to prevent conflicts
    groups:
      libs-updates:
        patterns:
          - "*"
        update-types:
          - "patch"
          - "minor"

  # =============================================================================
  # CONTAINERS - Individual service dependencies
  # =============================================================================

  # Content Collector - Web scraping and data ingestion
  - package-ecosystem: "pip"
    directory: "/containers/content-collector"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "06:00"
      timezone: "UTC"
    labels:
      - "dependencies"
      - "python"
      - "content-collector"
      - "auto-merge"
    open-pull-requests-limit: 3
    groups:
      collector-updates:
        patterns:
          - "*"
        update-types:
          - "patch"
          - "minor"

  # Site Generator - Static site generation
  - package-ecosystem: "pip"
    directory: "/containers/content-processor"
    schedule:
      interval: "weekly"
      day: "thursday"
      time: "06:00"
      timezone: "UTC"
    labels:
      - "dependencies"
      - "python"
      - "content-processor"
      - "auto-merge"
    open-pull-requests-limit: 2
    groups:
      processor-updates:
        patterns:
          - "*"
        update-types:
          - "patch"
          - "minor"

  # Site Generator - Static site generation
  - package-ecosystem: "pip"
    directory: "/containers/site-generator"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "06:00"
      timezone: "UTC"
    labels:
      - "dependencies"
      - "python"
      - "site-generator"
      - "auto-merge"
    open-pull-requests-limit: 2
    groups:
      site-gen-updates:
        patterns:
          - "*"
        update-types:
          - "patch"
          - "minor"

  # =============================================================================
  # FUNCTIONS - Azure Functions dependencies
  # =============================================================================

  # Static Site Deployer - Azure deployment function
  - package-ecosystem: "pip"
    directory: "/functions/static-site-deployer"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "06:00"
      timezone: "UTC"
    labels:
      - "dependencies"
      - "python"
      - "azure-functions"
      - "static-site-deployer"
      - "auto-merge"
    open-pull-requests-limit: 2
    groups:
      functions-updates:
        patterns:
          - "*"
        update-types:
          - "patch"
          - "minor"

  # =============================================================================
  # INFRASTRUCTURE - Actions and Docker images
  # =============================================================================

  # GitHub Actions - Workflow dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "06:00"
      timezone: "UTC"
    labels:
      - "dependencies"
      - "github-actions"
      - "infrastructure"
    open-pull-requests-limit: 3
    groups:
      actions-updates:
        patterns:
          - "*"
        update-types:
          - "patch"
          - "minor"
