# Dependabot configuration for AI Content Farm
# Features:
# - Auto-merge enabled for security updates and minor/patch versions
# - Manual review required for major version updates
# - Comprehensive testing via dependabot-automerge.yml workflow
# - Works with security scanning stack (Semgrep, Trivy, Checkov)
#
# Auto-merge criteria:
# - Security updates: Always auto-merged after CI validation
# - Patch/minor updates: Auto-merged after CI validation
# - Major updates: Require manual review
#
# Ref: https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Python dependencies - main workspace
  # - package-ecosystem: "pip"
  #   directory: "/"
  #   schedule:
  #     interval: "weekly"
  #     day: "monday"
  #     time: "06:00"
  #   labels:
  #     - "dependencies"
  #     - "python"
  #   reviewers:
  #     - "Hardcoreprawn"
  #   assignees:
  #     - "Hardcoreprawn"
  #   open-pull-requests-limit: 15
  #   # Enable auto-merge for security and patch updates
  #   pull-request-branch-name:
  #     separator: "/"

  # Python dependencies - container services
  # Python packages for libs
  - package-ecosystem: "pip"
    directory: "/libs"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    labels:
      - "dependencies"
      - "python"
      - "libs"
      - "auto-merge"
    open-pull-requests-limit: 5
    # Group related updates to reduce PR volume
    groups:
      python-minor-patches:
        patterns:
          - "*"
        update-types:
          - "patch"
          - "minor"

  # Python packages for containers/content-collector
  - package-ecosystem: "pip"
    directory: "/containers/content-collector"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    labels:
      - "dependencies"
      - "python"
      - "content-collector"
      - "auto-merge"
    open-pull-requests-limit: 5
    groups:
      python-minor-patches:
        patterns:
          - "*"
        update-types:
          - "patch"
          - "minor"

  - package-ecosystem: "pip"
    directory: "/containers/content-processor"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    labels:
      - "dependencies"
      - "python"
      - "content-processor"
      - "auto-merge"
    open-pull-requests-limit: 5
    groups:
      python-minor-patches:
        patterns:
          - "*"
        update-types:
          - "patch"
          - "minor"

  - package-ecosystem: "pip"
    directory: "/containers/content-enricher"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    labels:
      - "dependencies"
      - "python"
      - "content-enricher"
      - "auto-merge"
    open-pull-requests-limit: 5
    groups:
      python-minor-patches:
        patterns:
          - "*"
        update-types:
          - "patch"
          - "minor"

  - package-ecosystem: "pip"
    directory: "/containers/content-ranker"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    labels:
      - "dependencies"
      - "python"
      - "content-ranker"
      - "auto-merge"
    open-pull-requests-limit: 5
    groups:
      python-minor-patches:
        patterns:
          - "*"
        update-types:
          - "patch"
          - "minor"

  - package-ecosystem: "pip"
    directory: "/containers/content-generator"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    labels:
      - "dependencies"
      - "python"
      - "content-generator"
      - "auto-merge"
    open-pull-requests-limit: 5
    groups:
      python-minor-patches:
        patterns:
          - "*"
        update-types:
          - "patch"
          - "minor"

  - package-ecosystem: "pip"
    directory: "/containers/markdown-generator"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    labels:
      - "dependencies"
      - "python"
      - "markdown-generator"
      - "auto-merge"
    open-pull-requests-limit: 5
    groups:
      python-minor-patches:
        patterns:
          - "*"
        update-types:
          - "patch"
          - "minor"

  - package-ecosystem: "pip"
    directory: "/containers/site-generator"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    labels:
      - "dependencies"
      - "python"
      - "site-generator"
      - "auto-merge"
    open-pull-requests-limit: 5
    groups:
      python-minor-patches:
        patterns:
          - "*"
        update-types:
          - "patch"
          - "minor"

  - package-ecosystem: "pip"
    directory: "/containers/collector-scheduler"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    labels:
      - "dependencies"
      - "python"
      - "collector-scheduler"
      - "auto-merge"
    open-pull-requests-limit: 5
    groups:
      python-minor-patches:
        patterns:
          - "*"
        update-types:
          - "patch"
          - "minor"

  # # Docker base images
  # - package-ecosystem: "docker"
  #   directory: "/containers"
  #   schedule:
  #     interval: "monthly"
  #     day: "monday"
  #     time: "06:00"
  #   labels:
  #     - "dependencies"
  #     - "docker"
  #   open-pull-requests-limit: 10

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "06:00"
    labels:
      - "dependencies"
      - "github-actions"
    open-pull-requests-limit: 5
