name: 'Code Quality Checks'
description: 'Runs comprehensive code quality checks including formatting, linting, and type checking'
inputs:
  python-version:
    description: 'Python version to use'
    required: false
    default: '3.11'
  check-formatting:
    description: 'Run Black formatting checks'
    required: false
    default: 'true'
  check-imports:
    description: 'Run isort import sorting checks'
    required: false
    default: 'true'
  check-linting:
    description: 'Run flake8 linting checks'
    required: false
    default: 'true'
  check-types:
    description: 'Run mypy type checking'
    required: false
    default: 'false'
  check-complexity:
    description: 'Run pylint complexity analysis'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
        cache: 'pip'

    - name: Install Code Quality Tools
      shell: bash
      run: |
        echo "Installing code quality tools..."
        pip install flake8 black isort mypy pylint

    - name: Run Code Quality Checks
      shell: bash
      env:
        CHECK_FORMATTING: ${{ inputs.check-formatting }}
        CHECK_IMPORTS: ${{ inputs.check-imports }}
        CHECK_LINTING: ${{ inputs.check-linting }}
        CHECK_TYPES: ${{ inputs.check-types }}
        CHECK_COMPLEXITY: ${{ inputs.check-complexity }}
      run: |
        echo "Running code quality checks using shared script..."
        chmod +x ./scripts/code-quality.sh

        # Build the command based on inputs
        SCRIPT_ARGS=""

        if [[ "$CHECK_FORMATTING" == "true" && "$CHECK_IMPORTS" == "true" && "$CHECK_LINTING" == "true" ]]; then
          # Default case - run standard checks
          SCRIPT_ARGS=""
        else
          # Individual checks
          if [[ "$CHECK_FORMATTING" == "true" ]]; then
            SCRIPT_ARGS="$SCRIPT_ARGS --formatting"
          fi
          if [[ "$CHECK_IMPORTS" == "true" ]]; then
            SCRIPT_ARGS="$SCRIPT_ARGS --imports"
          fi
          if [[ "$CHECK_LINTING" == "true" ]]; then
            SCRIPT_ARGS="$SCRIPT_ARGS --linting"
          fi
        fi

        if [[ "$CHECK_TYPES" == "true" ]]; then
          SCRIPT_ARGS="$SCRIPT_ARGS --types"
        fi

        if [[ "$CHECK_COMPLEXITY" == "true" ]]; then
          SCRIPT_ARGS="$SCRIPT_ARGS --complexity"
        fi

        # If all checks are enabled, use --all flag
        if [[ "$CHECK_FORMATTING" == "true" && "$CHECK_IMPORTS" == "true" && "$CHECK_LINTING" == "true" && "$CHECK_TYPES" == "true" && "$CHECK_COMPLEXITY" == "true" ]]; then
          SCRIPT_ARGS="--all"
        fi

        # Run the script
        ./scripts/code-quality.sh $SCRIPT_ARGS
