# Yamllint configuration for ai-content-farm
extends: default

rules:
  line-length:
    max: 160
    level: warning
  truthy:
    check-keys: false
  comments:
    min-spaces-from-content: 1
  document-start:
    present: false
  indentation:
    indent-sequences: consistent
  braces:
    min-spaces-inside: 0
    max-spaces-inside: 1
  brackets:
    min-spaces-inside: 0
    max-spaces-inside: 1
  trailing-spaces: enable
  empty-lines:
    max: 2
  hyphens:
    max-spaces-after: 1
  colons:
    max-spaces-before: 0
    max-spaces-after: 1
