name: 'Auto-fix Code Formatting'
description: 'Automatically fixes code formatting and import sorting issues'
inputs:
  python-version:
    description: 'Python version to use'
    required: false
    default: '3.11'
  commit-changes:
    description: 'Whether to commit the formatting changes back to the branch'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
        cache: 'pip'

    - name: Install Formatting Tools
      shell: bash
      run: |
        echo "Installing code formatting tools..."
        pip install black isort

    - name: Auto-fix Code Formatting
      shell: bash
      run: |
        echo "[FORMAT] Auto-fixing code formatting issues..."

        # Run Black formatter
        echo "Running Black formatter..."
        black . || echo "Black formatting completed"

        # Run isort import sorting
        echo "Running isort import sorting..."
        isort . || echo "Import sorting completed"

        echo "[PASS] Code formatting auto-fix completed"

    - name: Check for Changes
      shell: bash
      id: check-changes
      run: |
        if git diff --quiet; then
          echo "No formatting changes needed"
          echo "has-changes=false" >> "$GITHUB_OUTPUT"
        else
          echo "Formatting changes were made"
          echo "has-changes=true" >> "$GITHUB_OUTPUT"
          echo "Changes made:"
          git diff --name-only
        fi

    - name: Commit Changes (if enabled)
      shell: bash
      if: inputs.commit-changes == 'true' && steps.check-changes.outputs.has-changes == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "style: auto-fix code formatting

        Applied Black code formatting and isort import sorting
        Automated by GitHub Actions"
        git push
