name: 'Sync Container Versions'
description: 'Compare GHCR container versions with Container Apps and update if newer'

inputs:
  registry:
    description: 'Container registry URL'
    required: true
  repository:
    description: 'Container repository name'
    required: true
  image-tag:
    description: 'New image tag to sync'
    required: true
  resource-group:
    description: 'Azure resource group name'
    required: true
  container-name:
    description: 'Specific container to sync (e.g., site-generator)'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Compare and Update Container Versions
      shell: bash
      env:
        INPUT_RESOURCE_GROUP: ${{ inputs.resource-group }}
        INPUT_IMAGE_TAG: ${{ inputs.image-tag }}
        INPUT_REGISTRY: ${{ inputs.registry }}
        INPUT_REPOSITORY: ${{ inputs.repository }}
        INPUT_CONTAINER_NAME: ${{ inputs.container-name }}
      run: |
        echo "[SYNC] Starting container version sync for specific container..."

        # Determine environment prefix from resource group
        if [[ "$INPUT_RESOURCE_GROUP" == *"prod"* ]]; then
          ENV_PREFIX="prod"
        else
          ENV_PREFIX="dev"
        fi

        # Container Apps mapping with dynamic environment prefix
        declare -A containers=(
          ["ai-content-${ENV_PREFIX}-collector"]="content-collector"
          ["ai-content-${ENV_PREFIX}-processor"]="content-processor"
          ["ai-content-${ENV_PREFIX}-site-generator"]="site-generator"
        )

        NEW_TAG="$INPUT_IMAGE_TAG"
        REGISTRY="$INPUT_REGISTRY"
        REPOSITORY="$INPUT_REPOSITORY"
        RESOURCE_GROUP="$INPUT_RESOURCE_GROUP"
        TARGET_CONTAINER="$INPUT_CONTAINER_NAME"

        echo "[INFO] Syncing container version:"
        echo "  Registry: $REGISTRY"
        echo "  Repository: $REPOSITORY"
        echo "  New Tag: $NEW_TAG"
        echo "  Resource Group: $RESOURCE_GROUP"
        echo "  Target Container: $TARGET_CONTAINER"
        echo

        # Find the Azure Container App name for this container
        app_name=""
        for container_app in "${!containers[@]}"; do
          if [[ "${containers[$container_app]}" == "$TARGET_CONTAINER" ]]; then
            app_name="$container_app"
            break
          fi
        done

        if [[ -z "$app_name" ]]; then
          echo "[ERROR] No Azure Container App found for container: $TARGET_CONTAINER"
          echo "Available containers: ${containers[@]}"
          exit 1
        fi

        echo "[SCAN] Checking $app_name ($TARGET_CONTAINER)..."

        # Get current container image from Container App
        current_image=$(az containerapp show \
          --name "$app_name" \
          --resource-group "$RESOURCE_GROUP" \
          --query "properties.template.containers[0].image" \
          --output tsv 2>/dev/null || echo "")

        if [[ -z "$current_image" ]]; then
          echo "  [WARN] Could not retrieve current image for $app_name, creating new deployment..."
          current_tag="none"
        else
          # Extract current tag
          current_tag=$(echo "$current_image" | sed 's/.*://')
        fi

        new_image="$REGISTRY/$REPOSITORY/$TARGET_CONTAINER:$NEW_TAG"

        echo "  [CURRENT] $current_image"
        echo "  [NEW]     $new_image"

        update_success=false
        if [[ "$current_tag" != "$NEW_TAG" ]]; then
          echo "  [UPDATE] Updating $app_name to tag $NEW_TAG..."

          # Update container app with new image
          az containerapp update \
            --name "$app_name" \
            --resource-group "$RESOURCE_GROUP" \
            --image "$new_image" \
            --output none

          if [[ $? -eq 0 ]]; then
            echo "  [PASS] Successfully updated $app_name"
            update_success=true
          else
            echo "  [FAIL] Failed to update $app_name"
            exit 1
          fi
        else
          echo "  [PASS] $app_name already at correct version"
          update_success=true
        fi

        echo "[COMPLETE] Container sync complete for $TARGET_CONTAINER!"

        # Add to job summary
        {
          echo "## Container Sync Results - $TARGET_CONTAINER"
          echo ""
          echo "| Container App | Current Image | Status |"
          echo "|---------------|---------------|--------|"
        } >> "$GITHUB_STEP_SUMMARY"

        # Get final image to confirm
        final_image=$(az containerapp show \
          --name "$app_name" \
          --resource-group "$RESOURCE_GROUP" \
          --query "properties.template.containers[0].image" \
          --output tsv 2>/dev/null || echo "Error")
        final_tag=$(echo "$final_image" | sed 's/.*://')

        if [[ "$final_tag" == "$NEW_TAG" ]]; then
          status="[PASS] Synced to $NEW_TAG"
        else
          status="[FAIL] Failed to sync"
        fi

        echo "| $app_name | $final_image | $status |" >> "$GITHUB_STEP_SUMMARY"

        echo "" >> "$GITHUB_STEP_SUMMARY"
        echo "**Total Updated:** $updated_count containers" >> "$GITHUB_STEP_SUMMARY"
