name: 'Detect Changes'
description: 'Detect what components changed to optimize CI/CD pipeline execution'
inputs:
  base-ref:
    description: 'Base reference for change detection'
    required: false
    default: 'HEAD~1'
  head-ref:
    description: 'Head reference for change detection'
    required: false
    default: 'HEAD'
  force-build-all:
    description: 'Force build all containers regardless of changes'
    required: false
    default: 'false'

outputs:
  containers-changed:
    description: 'Comma-separated list of containers that changed'
    value: ${{ steps.detect.outputs.containers }}
  infrastructure-changed:
    description: 'Whether infrastructure files changed'
    value: ${{ steps.detect.outputs.infrastructure }}
  libs-changed:
    description: 'Whether shared libs changed (affects all containers)'
    value: ${{ steps.detect.outputs.libs }}
  tests-changed:
    description: 'Whether test files changed'
    value: ${{ steps.detect.outputs.tests }}
  all-containers:
    description: 'Complete list of all containers in the project'
    value: ${{ steps.inventory.outputs.containers }}
  containers-json:
    description: 'JSON array of containers that changed (for matrix builds)'
    value: ${{ steps.inventory.outputs.containers-json }}
  build-matrix-json:
    description: 'JSON array of containers to build in matrix (changed containers or all if libs changed)'
    value: ${{ steps.inventory.outputs.build-matrix-json }}

runs:
  using: 'composite'
  steps:
    - name: Detect Changed Files
      id: detect
      shell: bash
      env:
        BASE_REF: ${{ inputs.base-ref }}
        HEAD_REF: ${{ inputs.head-ref }}
        GITHUB_EVENT_NAME: ${{ github.event_name }}
        GITHUB_BASE_SHA: ${{ github.event.pull_request.base.sha }}
        GITHUB_SHA: ${{ github.sha }}
        FORCE_BUILD_ALL: ${{ inputs.force-build-all }}
      run: |
        echo "[SCAN] Detecting changes between $BASE_REF and $HEAD_REF..."

        # Get list of changed files
        if [[ "$GITHUB_EVENT_NAME" == "pull_request" ]]; then
          changed_files=$(git diff --name-only "$GITHUB_BASE_SHA".."$GITHUB_SHA")
        else
          changed_files=$(git diff --name-only "$BASE_REF" "$HEAD_REF")
        fi

        echo "Changed files:"
        echo "$changed_files"

        # Detect container changes
        containers_changed=""

        # Force build all containers if requested
        if [[ "$FORCE_BUILD_ALL" == "true" ]]; then
          echo "Force build enabled - marking all containers as changed"
          for container_dir in containers/*/; do
            container_name=$(basename "$container_dir")
            if [ "$container_name" != "base" ]; then  # Exclude base directory
              if [ -z "$containers_changed" ]; then
                containers_changed="$container_name"
              else
                containers_changed="$containers_changed,$container_name"
              fi
            fi
          done
        else
          # Normal change detection
          for container_dir in containers/*/; do
            container_name=$(basename "$container_dir")
            if echo "$changed_files" | grep -q "^containers/$container_name/"; then
              if [ -z "$containers_changed" ]; then
                containers_changed="$container_name"
              else
                containers_changed="$containers_changed,$container_name"
              fi
            fi
          done
        fi

        # Detect other changes
        infra_changed="false"
        if echo "$changed_files" | grep -q "^infra/"; then
          infra_changed="true"
        fi

        libs_changed="false"
        if echo "$changed_files" | grep -q "^libs/"; then
          libs_changed="true"
        fi

        tests_changed="false"
        if echo "$changed_files" | grep -q "^tests/"; then
          tests_changed="true"
        fi

        {
          echo "containers=$containers_changed"
          echo "infrastructure=$infra_changed"
          echo "libs=$libs_changed"
          echo "tests=$tests_changed"
        } >> "$GITHUB_OUTPUT"

    - name: Container Inventory
      id: inventory
      shell: bash
      env:
        CONTAINERS_CHANGED: ${{ steps.detect.outputs.containers }}
        LIBS_CHANGED: ${{ steps.detect.outputs.libs }}
      run: |
        echo "[PACKAGE] Building complete container inventory..."
        all_containers=""
        containers_json="["
        first=true
        for container_dir in containers/*/; do
          container_name=$(basename "$container_dir")
          if [ "$container_name" != "base" ]; then  # Exclude base directory
            if [ -z "$all_containers" ]; then
              all_containers="$container_name"
            else
              all_containers="$all_containers,$container_name"
            fi

            # Build JSON array
            if [ "$first" = true ]; then
              containers_json="$containers_json\"$container_name\""
              first=false
            else
              containers_json="$containers_json,\"$container_name\""
            fi
          fi
        done
        containers_json="$containers_json]"

        # Determine build matrix (changed containers or all if libs changed)
        build_matrix_json=""
        if [ "$LIBS_CHANGED" = "true" ]; then
          # Build all containers if libs changed
          build_matrix_json="["
          first=true
          for container_dir in containers/*/; do
            container_name=$(basename "$container_dir")
            if [ "$container_name" != "base" ]; then
              if [ "$first" = true ]; then
                build_matrix_json="$build_matrix_json{\"container\":\"$container_name\"}"
                first=false
              else
                build_matrix_json="$build_matrix_json,{\"container\":\"$container_name\"}"
              fi
            fi
          done
          build_matrix_json="$build_matrix_json]"
          echo "[MATRIX] Building all containers due to libs change"
        elif [ -n "$CONTAINERS_CHANGED" ]; then
          # Build only changed containers
          build_matrix_json="["
          first=true
          IFS=',' read -ra CHANGED_CONTAINERS <<< "$CONTAINERS_CHANGED"
          for container in "${CHANGED_CONTAINERS[@]}"; do
            if [ "$first" = true ]; then
              build_matrix_json="$build_matrix_json{\"container\":\"$container\"}"
              first=false
            else
              build_matrix_json="$build_matrix_json,{\"container\":\"$container\"}"
            fi
          done
          build_matrix_json="$build_matrix_json]"
          echo "[MATRIX] Building changed containers: $CONTAINERS_CHANGED"
        else
          # No containers to build
          build_matrix_json="[]"
          echo "[MATRIX] No containers to build"
        fi

        echo "containers=$all_containers" >> "$GITHUB_OUTPUT"
        echo "containers-json=$containers_json" >> "$GITHUB_OUTPUT"
        echo "build-matrix-json=$build_matrix_json" >> "$GITHUB_OUTPUT"
        echo "All containers: $all_containers"
        echo "Containers JSON: $containers_json"
        echo "Build matrix JSON: $build_matrix_json"
