# Hugo Configuration for AI Content Farm
# Theme: PaperMod (https://github.com/adityatelange/hugo-PaperMod)

baseURL = "https://example.com/"  # Override via environment variable
languageCode = "en-us"
title = "AI Content Farm"
theme = "PaperMod"

# Build configuration
buildDrafts = false
buildFuture = false
buildExpired = false

# Output formats
[outputs]
  home = ["HTML", "RSS", "JSON"]

# Taxonomies
[taxonomies]
  tag = "tags"
  category = "categories"

# Pagination
[pagination]
  pagerSize = 12

# Menu
[[menu.main]]
  identifier = "home"
  name = "Home"
  url = "/"
  weight = 10

[[menu.main]]
  identifier = "posts"
  name = "Posts"
  url = "/posts/"
  weight = 20

[[menu.main]]
  identifier = "tags"
  name = "Tags"
  url = "/tags/"
  weight = 30

# PaperMod theme parameters
[params]
  env = "production"
  description = "AI-curated content from across the web"
  author = "AI Content Farm"

  # Analytics and monitoring
  analyticsEnabled = true  # Enable performance monitoring and telemetry

  # Application Insights configuration
  # These are populated from environment variables during build
  [params.appInsights]
    instrumentationKey = ""  # Populated from APPINSIGHTS_INSTRUMENTATION_KEY env var
    connectionString = ""    # Populated from APPLICATIONINSIGHTS_CONNECTION_STRING env var

  # Custom CSS for image sizing and layout
  [params.assets]
    customCSS = ["css/custom.css"]

  # Homepage configuration - provides H1 heading for SEO
  [params.homeInfoParams]
    Title = "AI Content Farm"
    Content = "AI-curated tech news and articles from across the web. Discover trending topics with automated fact-checking and research."

  # Show breadcrumbs
  ShowBreadCrumbs = true
  ShowPostNavLinks = true
  ShowCodeCopyButtons = true
  ShowRssButtonInSectionTermList = true

  # Search
  ShowSearchPage = true

  # Home page
  [[params.socialIcons]]
    name = "rss"
    url = "/index.xml"

# Markup configuration
[markup]
  [markup.highlight]
    style = "monokai"
    lineNos = true
    lineNumbersInTable = true
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = false  # Security: Don't allow raw HTML in markdown
