name: 'Build Multi-Tier Base Images'
description: 'Builds the multi-tier base images required for service containers'
inputs:
  registry:
    description: 'Container registry to tag images for (optional)'
    required: false
    default: ''
outputs:
  base-images-built:
    description: 'Comma-separated list of base images that were built'
    value: ${{ steps.build-bases.outputs.images }}

runs:
  using: 'composite'
  steps:
    - name: Build Multi-Tier Base Images
      id: build-bases
      shell: bash
      run: |
        echo "🏗️ Building multi-tier base images..."
        
        # Track built images
        built_images=""
        
        # Build each tier in dependency order
        base_images=(
          "foundation"
          "common-deps" 
          "web-services"
          "data-processing"
          "scheduler"
        )
        
        for tier in "${base_images[@]}"; do
          echo "Building $tier tier..."
          
          if docker build -f containers/base/Dockerfile.multitier \
             -t ai-content-farm-base:$tier \
             --target $tier .; then
            echo "✅ $tier base image built successfully"
            
            # Add to built images list
            if [ -z "$built_images" ]; then
              built_images="ai-content-farm-base:$tier"
            else
              built_images="$built_images,ai-content-farm-base:$tier"
            fi
            
            # Tag for registry if provided
            if [ -n "${{ inputs.registry }}" ]; then
              docker tag ai-content-farm-base:$tier ${{ inputs.registry }}/ai-content-farm-base:$tier
              echo "Tagged for registry: ${{ inputs.registry }}/ai-content-farm-base:$tier"
            fi
          else
            echo "❌ $tier base image build failed"
            exit 1
          fi
        done
        
        echo "✅ All base images built successfully: $built_images"
        echo "images=$built_images" >> $GITHUB_OUTPUT
