# Checkov security scanner configuration
framework:
  - terraform

skip-check:
  # Development environment reasonable exceptions
  - CKV_AZURE_165  # Geo-replication not required for dev/staging
  - CKV_AZURE_233  # Zone redundancy not required for dev (cost optimization)
  - CKV_AZURE_112  # HSM-backed keys require Premium Key Vault (cost)
  - CKV_AZURE_247  # OpenAI DLP configuration - requires enterprise setup
  - CKV2_AZURE_22  # Customer-managed encryption for OpenAI - complex setup

  # Service Bus encryption - disabled for development simplicity
  - CKV_AZURE_199  # Service Bus double encryption - disabled for dev
  - CKV_AZURE_201  # Service Bus customer-managed encryption - disabled for dev

  # Key Vault network access - allow all due to dynamic GitHub Actions IPs
  - CKV_AZURE_109  # Key Vault network ACLs - security enforced via RBAC instead

# Soft fail for info-level issues
soft-fail: true

# Baseline file for tracking issue evolution
baseline: .checkov.baseline
