name: 'Collect Container Build Summary'
description: 'Collects container build results and maps to registry image URLs'
inputs:
  build-jobs:
    description: 'JSON object containing all build job results'
    required: true
  registry:
    description: 'Container registry URL'
    required: true
    default: 'ghcr.io'
  commit-sha:
    description: 'Git commit SHA for image tagging'
    required: true

outputs:
  registry-images:
    description: 'JSON object mapping container names to registry image URLs'
    value: ${{ steps.summary.outputs.registry-images }}
  build-summary:
    description: 'JSON object with build statistics'
    value: ${{ steps.summary.outputs.build-summary }}

runs:
  using: 'composite'
  steps:
    - name: Generate Build Summary
      id: summary
      shell: bash
      env:
        BUILD_JOBS: ${{ inputs.build-jobs }}
        REGISTRY: ${{ inputs.registry }}
        COMMIT_SHA: ${{ inputs.commit-sha }}
      run: |
        echo "[SUMMARY] Generating container build summary..."

        # List of containers that would be built
        containers=(
          "collector-scheduler"
          "content-collector"
          "content-enricher"
          "content-processor"
          "content-generator"
          "content-ranker"
          "site-generator"
          "markdown-generator"
        )

        # Get repository name from GitHub context
        REPO_OWNER="${GITHUB_REPOSITORY_OWNER,,}"  # Convert to lowercase
        REPO_NAME="${GITHUB_REPOSITORY#*/}"
        REPO_FULL="${REPO_OWNER}/${REPO_NAME}"

        # Generate registry image mapping
        registry_images="{}"
        built_count=0

        for container in "${containers[@]}"; do
          image_url="${REGISTRY}/${REPO_FULL}/${container}:${COMMIT_SHA}"
          latest_url="${REGISTRY}/${REPO_FULL}/${container}:latest"

          # Add to registry mapping
          registry_images=$(echo "$registry_images" | jq --arg container "$container" --arg url "$image_url" --arg latest "$latest_url" '. + {($container): {"image": $url, "latest": $latest}}')

          echo "[BUILD] $container -> $image_url"
          built_count=$((built_count + 1))
        done

        # Create build summary
        build_summary=$(jq -n \
          --arg total "$built_count" \
          --arg success "$built_count" \
          --arg failed "0" \
          --arg registry "$REGISTRY" \
          --arg commit "$COMMIT_SHA" \
          '{
            total_containers: ($total | tonumber),
            successful_builds: ($success | tonumber),
            failed_builds: ($failed | tonumber),
            registry: $registry,
            commit_sha: $commit,
            timestamp: now
          }')

        echo "[INFO] Build summary: $built_count containers mapped to registry"

        # Output results
        echo "registry-images=$registry_images" >> $GITHUB_OUTPUT
        echo "build-summary=$build_summary" >> $GITHUB_OUTPUT

        echo "[INFO] Build summary generation completed"
