name: Lint Workflows
description: 'Validate GitHub Actions workflows and action files'
inputs:
  fail-on-error:
    description: 'Fail the build if linting errors are found'
    required: false
    default: 'true'

outputs:
  yamllint-passed:
    description: 'Whether yamllint validation passed'
    value: ${{ steps.yamllint.outputs.passed }}
  actionlint-passed:
    description: 'Whether actionlint validation passed'
    value: ${{ steps.set-actionlint-output.outputs.passed }}
  emoji-check-passed:
    description: 'Whether emoji check passed'
    value: ${{ steps.emoji-check.outputs.passed }}

runs:
  using: 'composite'
  steps:
    - name: Install linting tools
      shell: bash
      run: |
        echo "Installing workflow linting tools..."

        # Use containerized yamllint (cytopia/yamllint)
        echo "yamllint will be run via Docker container"

        # Use containerized actionlint (rhymond/actionlint)
        echo "actionlint will be run via Docker container"

    - name: Run yamllint
      id: yamllint
      shell: bash
      env:
        INPUT_FAIL_ON_ERROR: ${{ inputs.fail-on-error }}
      run: |
        echo "Running yamllint via Makefile..."

        # Use Makefile target for consistency
        if make yamllint; then
          echo "yamllint passed"
          echo "passed=true" >> $GITHUB_OUTPUT
        else
          echo "yamllint failed"
          echo "passed=false" >> $GITHUB_OUTPUT

          if [ "${INPUT_FAIL_ON_ERROR}" = "true" ]; then
            exit 1
          fi
        fi

    - name: Run actionlint
      id: actionlint
      shell: bash
      env:
        INPUT_FAIL_ON_ERROR: ${{ inputs.fail-on-error }}
      run: |
        echo "Running actionlint via Makefile..."

        # Use Makefile target for consistency
        if make actionlint; then
          echo "actionlint passed"
          echo "passed=true" >> $GITHUB_OUTPUT
        else
          echo "actionlint failed"
          echo "passed=false" >> $GITHUB_OUTPUT

          if [ "${INPUT_FAIL_ON_ERROR}" = "true" ]; then
            exit 1
          fi
        fi

    - name: Check for emojis in YAML files
      id: emoji-check
      shell: bash
      env:
        INPUT_FAIL_ON_ERROR: ${{ inputs.fail-on-error }}
      run: |
        echo "Running emoji check on YAML files..."

        # Run the emoji check script
        if ./scripts/check-emojis.sh; then
          echo "emoji-check passed"
          echo "passed=true" >> $GITHUB_OUTPUT
        else
          echo "emoji-check failed"
          echo "passed=false" >> $GITHUB_OUTPUT

          if [ "${INPUT_FAIL_ON_ERROR}" = "true" ]; then
            exit 1
          fi
        fi

    - name: Set actionlint output
      id: set-actionlint-output
      shell: bash
      run: |
        # Pass through actionlint status
        actionlint_status="${{ steps.actionlint.outputs.passed }}"
        echo "passed=$actionlint_status" >> $GITHUB_OUTPUT

        if [ "$actionlint_status" = "true" ]; then
          echo "actionlint passed"
        else
          echo "actionlint failed"
        fi

    - name: Generate Lint Report
      shell: bash
      run: |
        echo "Generating workflow lint report..."

        yamllint_status="${{ steps.yamllint.outputs.passed }}"
        actionlint_status="${{ steps.set-actionlint-output.outputs.passed }}"
        emoji_check_status="${{ steps.emoji-check.outputs.passed }}"

        cat > workflow-lint-report.md << EOF
        # Workflow Lint Report

        **Date**: $(date -u +"%Y-%m-%d %H:%M:%S UTC")

        ## Results
        - **yamllint**: $([ "$yamllint_status" = "true" ] && echo "Passed" || echo "Failed")
        - **actionlint**: $([ "$actionlint_status" = "true" ] && echo "Passed" || echo "Failed")
        - **emoji-check**: $([ "$emoji_check_status" = "true" ] && echo "Passed" || echo "Failed")

        ## Summary
        $([ "$yamllint_status" = "true" ] && [ "$actionlint_status" = "true" ] && [ "$emoji_check_status" = "true" ] && echo "All workflow linting checks passed!" || echo "Some linting issues were found - check the logs above for details.")

        ### Emoji Check
        The emoji check ensures that no emojis are used in YAML files, as they can cause encoding issues in CI/CD pipelines and complicate automation scripts.

        EOF

    - name: Upload Lint Report
      uses: actions/upload-artifact@v4
      with:
        name: workflow-lint-report
        path: workflow-lint-report.md
        retention-days: 7
