name: Lint Workflows
description: 'Validate GitHub Actions workflows and action files'
inputs:
  fail-on-error:
    description: 'Fail the build if linting errors are found'
    required: false
    default: 'true'

outputs:
  yamllint-passed:
    description: 'Whether yamllint validation passed'
    value: ${{ steps.yamllint.outputs.passed }}
  actionlint-passed:
    description: 'Whether actionlint validation passed'
    value: ${{ steps.actionlint.outputs.passed }}

runs:
  using: 'composite'
  steps:
    - name: Install linting tools
      shell: bash
      run: |
        echo "🔧 Installing workflow linting tools..."

        # Use containerized yamllint (cytopia/yamllint)
        echo "📝 yamllint will be run via Docker container"

        # Use containerized actionlint (rhymond/actionlint)
        echo "🔍 actionlint will be run via Docker container"

    - name: Run yamllint
      id: yamllint
      shell: bash
      run: |
        echo "🔍 Running yamllint on workflow files..."

        # Verify our yamllint config exists
        if [ -f .yamllint.yml ]; then
          echo "📋 Using existing .yamllint.yml configuration"
          cat .yamllint.yml
        else
          echo "⚠️ No .yamllint.yml found, yamllint will use defaults"
        fi

        # Run yamllint via Docker, mounting our config file
        if docker run --rm -v ${{ github.workspace }}:/workspace \
          cytopia/yamllint:latest -c /workspace/.yamllint.yml /workspace/.github/; then
          echo "✅ yamllint passed"
          echo "passed=true" >> $GITHUB_OUTPUT
        else
          echo "❌ yamllint failed"
          echo "passed=false" >> $GITHUB_OUTPUT

          if [ "${{ inputs.fail-on-error }}" = "true" ]; then
            exit 1
          fi
        fi

    - name: Run actionlint
      id: actionlint
      shell: bash
      run: |
        echo "🔍 Running actionlint on GitHub Actions..."

        # Run actionlint via Docker container (consistent with other tools)
        if docker run --rm -v ${{ github.workspace }}:/workspace \
          rhymond/actionlint:latest -color \
          /workspace/.github/workflows/*.yml /workspace/.github/actions/*/action.yml; then
          echo "✅ actionlint passed"
          echo "passed=true" >> $GITHUB_OUTPUT
        else
          echo "❌ actionlint failed"
          echo "passed=false" >> $GITHUB_OUTPUT

          if [ "${{ inputs.fail-on-error }}" = "true" ]; then
            exit 1
          fi
        fi

    - name: Generate Lint Report
      shell: bash
      run: |
        echo "📋 Generating workflow lint report..."

        yamllint_status="${{ steps.yamllint.outputs.passed }}"
        actionlint_status="${{ steps.actionlint.outputs.passed }}"

        cat > workflow-lint-report.md << EOF
        # Workflow Lint Report

        **Date**: $(date -u +"%Y-%m-%d %H:%M:%S UTC")

        ## Results
        - **yamllint**: $([ "$yamllint_status" = "true" ] && echo "✅ Passed" || echo "❌ Failed")
        - **actionlint**: $([ "$actionlint_status" = "true" ] && echo "✅ Passed" || echo "❌ Failed")

        ## Summary
        $([ "$yamllint_status" = "true" ] && [ "$actionlint_status" = "true" ] && echo "All workflow linting checks passed!" || echo "Some linting issues were found - check the logs above for details.")

        EOF

    - name: Upload Lint Report
      uses: actions/upload-artifact@v4
      with:
        name: workflow-lint-report
        path: workflow-lint-report.md
        retention-days: 7
