[tool.pytest.ini_options]
minversion = "6.0"
testpaths = ["tests"]
markers = [
    "unit: Unit tests (fast, isolated)",
    "integration: Integration tests (slower, external dependencies)",
    "performance: Performance tests (timing sensitive)",
]
addopts = [
    "--strict-markers",
    "--disable-warnings",
    "-v"
]
filterwarnings = [
    "ignore::DeprecationWarning",
    "ignore::PendingDeprecationWarning",
]

[tool.black]
line-length = 88
target-version = ['py311']

# Removed [tool.isort] section to inherit from root .isort.cfg
# This ensures consistent import sorting across all containers
