[tool.pytest.ini_options]
testpaths = ["tests"]
markers = [
    "unit: Unit tests (fast, mocked dependencies)",
    "integration: Integration tests (slower, real dependencies)",
    "performance: Performance tests"
]
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "function"

[tool.pytest.timeout]
timeout = 300

[tool.coverage.run]
source = ["."]
omit = [
    "tests/*",
    "venv/*",
    ".venv/*",
    "__pycache__/*"
]
