[tool.pytest.ini_options]
testpaths = ["tests"]
markers = [
    "unit: Fast unit tests with mocked dependencies",
    "api: FastAPI endpoint tests", 
    "integration: Fast integration tests with contract-based mocking",
    "slow: Slow tests (20+ minutes) - only run when specifically requested"
]
filterwarnings = [
    "ignore::pytest.PytestDeprecationWarning",
    "ignore::DeprecationWarning"
]
asyncio_mode = "auto"

# Test discovery patterns
python_files = ["test_*.py", "*_test.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]

# Exclude slow tests by default
addopts = "-v --tb=short -m 'not slow'"
