[tool.pytest.ini_options]
minversion = "6.0"
testpaths = ["tests"]
markers = [
    "unit: marks tests as unit tests (fast, no external dependencies)",
    "integration: marks tests as integration tests (require Azure services)",
    "slow: marks tests as slow running (performance tests)",
]
addopts = [
    "--strict-markers",
    "--disable-warnings",
    "-v"
]
filterwarnings = [
    "ignore::DeprecationWarning",
    "ignore::PendingDeprecationWarning",
]
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "function"

[tool.black]
line-length = 88
target-version = ['py311']

# Removed [tool.isort] section to inherit from root .isort.cfg
# This ensures consistent import sorting across all containers
