name: 'Python Security Scan'
description: 'Run Python security scanning with Safety'
inputs:
  workspace-path:
    description: 'Path to the workspace'
    required: true
    default: ${{ github.workspace }}

runs:
  using: 'composite'
  steps:
    - name: Create Security Results Directory
      shell: bash
      run: mkdir -p security-results

    - name: Check for Python Requirements
      id: check-requirements
      shell: bash
      run: |
        if find . -name "requirements.txt" -type f | grep -q .; then
          echo "found=true" >> "$GITHUB_OUTPUT"
        else
          echo "found=false" >> "$GITHUB_OUTPUT"
          echo "No requirements.txt files found, skipping Python security scan"
        fi

    - name: Run Python Security Scan
      if: steps.check-requirements.outputs.found == 'true'
      uses: ./.github/actions/safety-config
      with:
        mode: 'scan'
        output-format: 'json'
        output-dir: 'security-results'

    - name: Upload Python Security Results
      if: steps.check-requirements.outputs.found == 'true'
      uses: actions/upload-artifact@v4
      with:
        name: security-results-python
        path: security-results/safety-*.json
        retention-days: 30
