---
name: Scheduled Content Collection

on:
  schedule:
    # Run every 4 hours at minute 0: 00:00, 04:00, 08:00, 12:00, 16:00, 20:00 UTC
    - cron: '0 */4 * * *'
  workflow_dispatch:  # Allow manual triggering

permissions:
  contents: read
  id-token: write

env:
  AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

jobs:
  trigger-content-collection:
    name: Trigger Content Collection
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'  # Only run on main branch

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Get Container App URL
        id: get-url
        run: |
          # Get the content collector container app URL
          URL=$(az containerapp show \
            --name "ai-content-dev-collector" \
            --resource-group "ai-content-dev-rg" \
            --query "properties.configuration.ingress.fqdn" \
            --output tsv)

          if [ -z "$URL" ]; then
            echo "[FAIL] Failed to get container app URL"
            exit 1
          fi

          echo "CONTENT_COLLECTOR_URL=https://$URL" >> "$GITHUB_OUTPUT"
          echo "[PASS] Content Collector URL: https://$URL"

      - name: Send Collection Request to Service Bus
        run: |
          # Create collection request payload
          cat > collection_request.json << 'EOF'
          {
            "service_name": "github-actions",
            "operation": "collect_content",
            "payload": {
              "sources": [
                {
                  "type": "reddit",
                  "subreddits": ["technology", "programming", "artificial", "MachineLearning"],
                  "limit": 25
                },
                {
                  "type": "rss",
                  "urls": [
                    "https://feeds.feedburner.com/oreilly/radar",
                    "https://aws.amazon.com/blogs/aws/feed/"
                  ],
                  "limit": 15
                }
              ],
              "deduplicate": true,
              "similarity_threshold": 0.8,
              "save_to_storage": true
            },
            "metadata": {
              "triggered_by": "github_actions",
              "workflow": "${{ github.workflow }}",
              "run_id": "${{ github.run_id }}",
              "timestamp": "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
            }
          }
          EOF

          echo "[INFO] Collection request payload:"
          jq . collection_request.json

      - name: Send Service Bus Message
        run: |
          # Use HTTP call instead of Service Bus CLI (which has limited support)
          # Call the content collector directly to trigger collection via Service Bus
          curl -X POST "${{ steps.get-url.outputs.CONTENT_COLLECTOR_URL }}/collections" \
            -H "Content-Type: application/json" \
            -d @collection_request.json \
            -w "HTTP Status: %{http_code}\n"

          echo "[PASS] Content collection request sent via HTTP API"
          echo "[INFO] This triggers internal Service Bus processing and KEDA scaling"

      - name: Verify Collection Status
        run: |
          # Check the health and status of our collection
          echo "[INFO] Checking collection status..."

          curl -s "${{ steps.get-url.outputs.CONTENT_COLLECTOR_URL }}/status" | jq .

          echo "[PASS] Collection status checked"

      - name: Log Completion
        run: |
          echo "[COMPLETE] Content collection workflow completed"
          echo "[SCHEDULE] Next scheduled run: $(date -d '+4 hours' -u '+%Y-%m-%d %H:%M:%S UTC')"
          echo "[MONITOR] Monitor processing at: ${{ steps.get-url.outputs.CONTENT_COLLECTOR_URL }}/health"
