name: Auto-Approve Dependabot PRs

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  pull-requests: write
  contents: read

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Auto-approve Dependabot PR
        run: |
          echo "Auto-approving Dependabot PR #${{ github.event.pull_request.number }}"
          gh pr review ${{ github.event.pull_request.number }} --approve --body "[AUTO-APPROVED] **Auto-approved** - Dependabot dependency update automatically approved by workflow."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
