name: 'Dependabot Auto-merge'
on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: write
  pull-requests: write
  security-events: write

jobs:
  dependabot-checks:
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Basic security scan
        uses: ./.github/actions/security-scan
        with:
          fail-on-critical: 'false'
          upload-sarif: 'true'
          environment: 'staging'

      - name: Check for major version updates
        id: version-check
        run: |
          if [[ "${{ steps.metadata.outputs.update-type }}" == "version-update:semver-major" ]]; then
            echo "is-major=true" >> "$GITHUB_OUTPUT"
            echo "[WARN] Major version update detected - manual review recommended"
          else
            echo "is-major=false" >> "$GITHUB_OUTPUT"
            echo "[PASS] Safe dependency update (patch/minor)"
          fi

      - name: Enable auto-merge (non-major updates)
        if: steps.version-check.outputs.is-major == 'false'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          echo "[AUTO-MERGE] Enabling auto-merge for safe dependency update"
          gh pr comment "$PR_NUMBER" --body "[AUTO-MERGE] **Safe dependency update** - Auto-merge enabled for ${{ steps.metadata.outputs.update-type }} update."
          gh pr merge "$PR_NUMBER" --auto --squash --delete-branch

      - name: Request review for major updates
        if: steps.version-check.outputs.is-major == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          echo "[REVIEW] Major version update requires manual review"
          gh pr comment "$PR_NUMBER" --body "[REVIEW REQUIRED] **Major version update detected**

          This PR updates **${{ steps.metadata.outputs.dependency-names }}** with a major version change (${{ steps.metadata.outputs.update-type }}).

          **Why manual review is needed:**
          - Major versions may include breaking changes
          - API changes could affect functionality
          - Testing may be required to ensure compatibility

          **Next steps:**
          1. Review the changelog for breaking changes
          2. Test locally if needed
          3. Approve and merge manually when ready

          Security scan has passed, so this update is safe from a security perspective."
