name: 'Dependabot Auto-merge'
on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: write
  pull-requests: write
  checks: read

jobs:
  dependabot-auto-merge:
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Validate workflows
        run: |
          echo "[SCAN] Validating workflow syntax..."
          # Reuse existing make target for consistency
          make lint-workflows

      - name: Quick container validation
        uses: ./.github/actions/validate-containers
        with:
          fail-fast: 'true'

      - name: Run security scan
        uses: ./.github/actions/security-scan
        with:
          fail-on-critical: 'false'  # Don't fail on security issues for dependency updates
          upload-sarif: 'false'
          environment: 'staging'

      - name: Enable auto-merge for Dependabot PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          echo "[AUTO-MERGE] Enabling auto-merge for Dependabot PR #$PR_NUMBER"

          # Add informative comment
          gh pr comment "$PR_NUMBER" --body "[AUTO-MERGE] **Dependabot Auto-merge enabled** - This PR will auto-merge when CI checks pass."

          # Enable auto-merge with squash strategy
          gh pr merge "$PR_NUMBER" --auto --squash --delete-branch
