name: Auto-Label and Approve Dependabot PRs

on:
  pull_request:
    types: [opened]

permissions:
  pull-requests: write
  contents: read

jobs:
  auto-label-and-approve:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Add auto-merge label to Dependabot PRs
        run: |
          gh pr edit ${{ github.event.number }} --add-label "auto-merge"
          echo "Added auto-merge label to Dependabot PR #${{ github.event.number }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Auto-approve safe Dependabot PRs
        if: |
          steps.metadata.outputs.update-type == 'version-update:semver-patch' ||
          steps.metadata.outputs.update-type == 'version-update:semver-minor' ||
          steps.metadata.outputs.update-type == 'version-update:semver-security'
        run: |
          gh pr review ${{ github.event.number }} --approve --body "[AUTO-APPROVED] Portfolio automation approved this PR

          This Dependabot PR has been automatically approved because:
          - [PASS] It's a safe dependency update (${{ steps.metadata.outputs.update-type }})
          - [PASS] Only affects dependency files
          - [PASS] Will be tested by CI/CD pipeline

          **Dependencies updated:**
          ${{ steps.metadata.outputs.dependency-names }}

          If CI passes, this will auto-merge via the existing auto-merge workflow."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Comment on major version updates
        if: steps.metadata.outputs.update-type == 'version-update:semver-major'
        run: |
          gh pr comment ${{ github.event.number }} --body "[WARN] Major version update detected - Manual review required

          This PR contains potentially breaking changes and will not be auto-approved.

          **Update details:**
          - Dependencies: ${{ steps.metadata.outputs.dependency-names }}
          - Type: ${{ steps.metadata.outputs.update-type }}

          Please review the changelog and test thoroughly before approving and merging."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
