name: 'Dependabot Auto-merge'
on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: write
  pull-requests: write
  checks: read

jobs:
  dependabot-auto-merge:
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Validate workflows
        run: |
          echo "🔍 Validating workflow syntax..."
          # Reuse existing make target for consistency
          make lint-workflows

      - name: Quick container validation
        uses: ./.github/actions/validate-containers
        with:
          fail-fast: 'true'

      - name: Run security scan
        uses: ./.github/actions/security-scan
        with:
          fail-on-critical: 'true'
          upload-sarif: 'false'
          environment: 'staging'

      - name: Check if PR is ready for auto-merge
        id: check-ready
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
          PR_BODY: ${{ github.event.pull_request.body }}
        run: |
          echo "🤖 Checking Dependabot PR readiness..."

          # Check for security updates (higher priority)
          if echo "$PR_TITLE" | grep -i "security\|vulnerability\|cve"; then
            echo "🚨 Security update detected - prioritizing auto-merge"
            echo "is-security=true" >> "$GITHUB_OUTPUT"
            echo "should-auto-merge=true" >> "$GITHUB_OUTPUT"
          # Check for patch/minor updates (safe to auto-merge)
          elif echo "$PR_TITLE" | grep -E "(patch|minor).*update|bump.*\([0-9]+\.[0-9]+\.[0-9]+\)"; then
            echo "🔄 Patch/minor update detected - safe for auto-merge"
            echo "is-security=false" >> "$GITHUB_OUTPUT"
            echo "should-auto-merge=true" >> "$GITHUB_OUTPUT"
          # Major updates require manual review
          elif echo "$PR_TITLE" | grep -i "major.*update"; then
            echo "⚠️  Major update detected - requires manual review"
            echo "is-security=false" >> "$GITHUB_OUTPUT"
            echo "should-auto-merge=false" >> "$GITHUB_OUTPUT"
          else
            echo "🔍 Standard dependency update - safe for auto-merge"
            echo "is-security=false" >> "$GITHUB_OUTPUT"
            echo "should-auto-merge=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Enable auto-merge
        if: steps.check-ready.outputs.should-auto-merge == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          IS_SECURITY: ${{ steps.check-ready.outputs.is-security }}
        run: |
          echo "✅ Enabling auto-merge for Dependabot PR"

          # Add informative comment
          if [ "$IS_SECURITY" = "true" ]; then
            comment="🚨 **Security Update Auto-merge** - This PR contains security fixes and will be auto-merged after CI validation."
          else
            comment="🤖 **Dependabot Auto-merge** - This PR will be auto-merged after successful CI validation."
          fi

          gh pr comment "$PR_NUMBER" --body "$comment"

          # Enable auto-merge with squash strategy
          gh pr merge "$PR_NUMBER" --auto --squash

      - name: Manual review required
        if: steps.check-ready.outputs.should-auto-merge == 'false'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          echo "⚠️  Manual review required for this PR"

          comment="⚠️  **Manual Review Required** - This PR contains major updates that require manual review before merging. Please review the changes and merge manually if appropriate."

          gh pr comment "$PR_NUMBER" --body "$comment"
