name: YAML and Actions Lint

on:
  push:
    paths:
      - '.github/workflows/**/*.yml'
      - '.github/workflows/**/*.yaml'
      - '.yamllint.yaml'
  pull_request:
    paths:
      - '.github/workflows/**/*.yml'
      - '.github/workflows/**/*.yaml'
      - '.yamllint.yaml'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install yamllint
        run: pip install yamllint

      - name: Run yamllint
        run: yamllint -f colored .

      - name: Run actionlint
        uses: docker://rhysd/actionlint:latest
        with:
          args: -color
